version: '2'
services:  
  database:
    build: ./database
    ports:
      - "3306:3306"

  webapp:
    build: ./webapp
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
